CREATE EXTERNAL TABLE IF NOT EXISTS `{{ params.project_id }}.baseball.events`
OPTIONS(
  format="CSV",
  uris=["gs://{{ params.bucket }}/{{ params.folder }}/*/ouput.csv"]
);
CREATE OR REPLACE VIEW `{{ params.project_id}}.baseball.pitches`
AS SELECT
  game_pk,
  at_bat_number,
  pitch_number,
  game_date,
  game_type,
  home_team,
  away_team,
  inning,
  balls,
  strikes,
  outs_when_up,
  batter,
  pitcher,
  CONCAT(
    SPLIT(player_name, ',')[OFFSET(1)],
    " ",
    SPLIT(player_name, ',')[OFFSET(0)]
  ) as pitcher_name,
  pitch_type,
  release_speed,
  release_spin_rate,
  release_pos_x,
  release_pos_z,
  release_pos_y,
  vx0,
  vy0,
  vz0,
  ax,
  ay,
  az,
  plate_x,
  plate_z,
  pfx_x,
  pfx_z,
  release_extension,
  effective_speed,
  sz_top,
  sz_bot,
  zone,
  stand,
  p_throws,
  on_1b,
  on_2b,
  on_3b,
  fielder_2,
  fielder_3,
  fielder_4,
  fielder_5,
  fielder_6,
  fielder_7,
  fielder_8,
  fielder_9,
  events,
  type,
  bb_type,
  hit_location,
  hit_distance_sc,
  launch_speed,
  launch_angle,
  hc_x,
  hc_y,
  estimated_ba_using_speedangle,
  estimated_woba_using_speedangle,
  woba_value,
  woba_denom,
  babip_value,
  iso_value,
  home_score,
  away_score,
  bat_score,
  fld_score,
  post_home_score,
  post_away_score,
  post_bat_score,
  post_fld_score,
  if_fielding_alignment,
  of_fielding_alignment,
  delta_run_exp as rv
FROM
  `itam-spring-2022.baseball.events`
;
